#IDW ants####
idw1_Mrub_sum<-idw(Mrub_sum ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Msca_sum<-idw(Msca_sum ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Mrug_sum<-idw(Mrug_sum ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Msch_sum<-idw(Msch_sum ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_oth_sum<-idw(oth_sum ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Mrub_max<-idw(Mrub_max ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Msca_max<-idw(Msca_max ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Mrug_max<-idw(Mrug_max ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Msch_max<-idw(Msch_max ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_oth_max<-idw(oth_max ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Mrub_pres<-idw(Mrub_pres ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Msca_pres<-idw(Msca_pres ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Mrug_pres<-idw(Mrug_pres ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Msch_pres<-idw(Msch_pres ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_oth_pres<-idw(oth_pres ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_allM_sum<-idw(allM_sum ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_allM_max<-idw(allM_max ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_allM_pres<-idw(allM_pres ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Mrub_rug_s<-idw(Mrub_rug_s ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Mrub_rug_m<-idw(Mrub_rug_m ~ 1, data_pts, grd1, idp = 1, maxdist=3)
idw1_Mrub_rug_p<-idw(Mrub_rug_p ~ 1, data_pts, grd1, idp = 1, maxdist=3)

